import { useContext, useRef, useState } from 'react';
import { Box, Stack, Switch, Tooltip, Typography } from '@mui/material';
import { InfoOutlined } from '@mui/icons-material';
import { useRouter } from 'next/router';
import { logError } from '@/common/utils';
import { marked } from 'marked';
import AppContext from '@/common/context';

export default function useSummary() {
  const [content, setContent] = useState('');
  const { summaryOn, setContext } = useContext(AppContext);
  const { pathname } = useRouter();
  const controlRef = useRef(null);

  const explain = async (prompt) => {
    if (!summaryOn) return;
    controlRef.current?.abort();
    const controller = new AbortController();
    controlRef.current = controller;
    setContent('<p>Thinking...</p>');
    try {
      const res = await fetch('/api/summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt, pathname }),
        signal: controller.signal,
      });
      if (res.ok) {
        const html = marked(await res.text());
        setContent(html);
      } else {
        setContent(
          res.status === 504
            ? '<p>AI request timed out.</p>'
            : '<p>AI request failed. Please try again later.</p>',
        );
      }
    } catch (err) {
      if (err.name !== 'AbortError') {
        setContent('<p>Something went wrong. Please try again.</p>')
      }
      logError({
        title: 'AI request cancelled',
        message: err.message,
        page: pathname,
      });
    }
  };

  const toggle = (e) => {
    const { checked } = e.target;
    setContext({ summaryOn: checked });
    if (!checked) abort();
  };

  const abort = () => {
    controlRef.current?.abort();
    setContent('');
  };

  const summary = (
    <Stack minHeight={200}>
      <Box display="flex" alignItems="center" gap={1}>
        <Typography variant="h6" component="h2">
          AI Summary
        </Typography>
        <Tooltip title="This summary is generated by AI and can be inaccurate.">
          <InfoOutlined fontSize="small" color="warning" />
        </Tooltip>
        <Switch
          size="small"
          checked={summaryOn}
          onChange={toggle}
          inputProps={{ 'aria-label': 'AI Summary Toggle' }}
        />
      </Box>
      <Typography
        variant="body2"
        maxWidth="sm"
        minWidth={500}
        lineHeight={1.6}
        dangerouslySetInnerHTML={{ __html: content }}
      />
    </Stack>
  );

  return [summary, explain, abort];
}
