import { useRef, useState } from 'react';
import { Box, Stack, Tooltip, Typography } from '@mui/material';
import { InfoOutlined } from '@mui/icons-material';
import { logError } from '@/common/utils';
import { marked } from 'marked';
import { useRouter } from 'next/router';

export default function useSummary() {
  const [content, setContent] = useState('');
  const { pathname } = useRouter();
  const controlRef = useRef(null);

  const explain = (prompt) => {
    setContent('<p>Thinking...</p>');
    if (controlRef.current) controlRef.current.abort();
    const controller = new AbortController();
    controlRef.current = controller;

    fetch('/api/summary', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt, pathname }),
      signal: controller.signal,
    })
      .then((res) => res.text())
      .then((text) => {
        setContent(marked(text));
      })
      .catch((err) => {
        logError({
          title: 'AI request cancelled',
          message: err.message,
          page: pathname,
        });
      });
  };

  const summary = (
    <Stack minHeight={200}>
      <Box display="flex" alignItems="center" gap={1}>
        <Typography variant="h6" component="h2">
          AI Summary
        </Typography>
        <Tooltip title="This summary is generated by AI and can be inaccurate.">
          <InfoOutlined fontSize="small" color="warning" />
        </Tooltip>
      </Box>
      <Typography
        variant="body2"
        maxWidth="sm"
        minWidth={500}
        lineHeight={1.6}
        dangerouslySetInnerHTML={{ __html: content }}
      />
    </Stack>
  );

  return [summary, explain];
}
