export const Colors = {
  white: '#FFFFFF',
  compare: '#ffc107',
  sorted: '#aed581',
  vertex: '#e5e5e5',
  stroke: '#424242',
  enqueue: '#2196f3',
  rejected: '#c5c5c5',
  visited: '#ff9800',
};

export const Algorithms = {
  BubbleSort: 'Bubble Sort',
  InsertionSort: 'Insertion Sort',
  SelectionSort: 'Selection Sort',
  RadixSort: 'Radix Sort',
  HeapSort: 'Heap Sort',
  MergeSort: 'Merge Sort',
  QuickSort: 'Quick Sort',
  DFS: 'Depth First Search',
  BFS: 'Breadth First Search',
  PrimsMST: "Prim's Algorithm",
  KruskalsMST: "Kruskal's Algorithm",
  Dijkstra: "Dijkstra's Algorithm",
  TopSort: 'Topological Sorting',
  BST: 'Binary Search Tree',
  BinaryHeap: 'Binary Heap',
  CircularQueue: 'Circular Queue',
  ConvexHull: 'Convex Hull',
  Hamiltonian: 'Hamiltonian Cycle',
};
